version: '3.8'

services:
  demo-db:
    image: postgres:10.2
    container_name: demo-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - .volumes/decor/data:/var/lib/postgresql/data