server:
  port: 8080
  servlet:
    session:
      cookie:
        max-age: -1

spring:
  profiles:
    active: default
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/example
    driver-class-name: org.postgresql.Driver
    schema: classpath:db/schema.sql
    initialization-mode: always
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate.ddl-auto: none
    properties:
      javax.persistence.validation.mode: none
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  flyway:
    enabled: true
    schemas: public_flyway